fix(jira): aligned regular expression
uwu-tools/gh-jira-issue-sync pull request #211
Opened 2023-11-07 21:44 UTC by lgecse

Fixes #9 

Updated regular expression to match with:
- comments created by bots ( GitHubUser.GetName() can be empty, making the regex not match with the comment ) [internal/jira/jira.go ln337](https://github.com/uwu-tools/gh-jira-issue-sync/blob/ee1bd0b658ec9590f310db7b4a748055b6aae7fb/internal/jira/jira.go#L337)
- comments with having new lines in them 

Examples:

>Comment [(ID 1793589510)|https://github.com/openclarity/vmclarity/issues/632#issuecomment-1793589510] from GitHub user [github-actions[bot]|https://github.com/apps/github-actions] at 00:19 AM, November 5 2023:
>
>Thank you for your contribution! This issue has been automatically marked as `stale` because it has no recent activity in the last 60 days. It will be closed in 14 days, if no further activity occurs. If this issue is still relevant, please leave a comment to let us know, and the `stale` label will be automatically removed.`

>Comment [(ID 1787170117)|https://github.com/openclarity/vmclarity/issues/812#issuecomment-1787170117] from GitHub user [lgecse|https://github.com/lgecse] (Laszlo Gecse) at 12:58 PM, October 31 2023:
>
>- Rename the PATH to INPUT
>- Have separate views based on the TYPE
>- In case of sbom it'd have the SIZE field 
>- In case of csv it'd have the number of items 
>- Make the list expandable, for cases when it'd be too long`

2023-11-14 08:56 UTC, justaugustus requested changes
@lgecse – nice catch! Would you mind adding a test case or two for this as well?

2023-11-14 18:41 UTC, justaugustus reviewed
@lgecse – looks good, just needs a branch update so I can approve :)

2023-11-17 08:57 UTC, cpanato approved these changes
lgtm

2023-11-18 07:58 UTC, justaugustus approved these changes

2023-11-18 08:00 UTC, merged